name: CI

on:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pipeline
      run: |
        rm indian-passwords-length8-20 indian-passwords-length8-20-sorted
        sort indian-passwords > indian-passwords-sorted
        while read -r line; do chars=${#line}; if [[ $chars -ge 8 ]] && [[ $chars -le 20 ]]; then echo $line; fi; done < indian-passwords >> indian-passwords-length8-20
        sort indian-passwords-length8-20 > indian-passwords-length8-20-sorted
        
        # Generate stats
        rm -f STATS.md
        echo -e "|wc -l|\n|---|" > STATS.md
        wc -l indian-passwords | sed 's/.*/|&|/' >> STATS.md
        wc -l indian-passwords-length8-20 | sed 's/.*/|&|/' >> STATS.md
        wc -l indian-passwords-length8-20-sorted | sed 's/.*/|&|/' >> STATS.md
        wc -l indian-passwords-sorted | sed 's/.*/|&|/' >> STATS.md

    - name: Gitback
      run: |
        git config --global user.email "ci@zxcv32.com"
        git config --global user.name "CI zxcV32"
        git remote add github "https://github.com/zxcV32/indian-wordlist.git"
        git add .
        git commit -m "Auto commit by pipeline"
        git push github main
